In [1]:
import numpy as np

In [9]:
a = np.random.randn(2, 3, 2, 2)
a.shape

(2, 3, 2, 2)

In [11]:
a

array([[[[-0.69353221,  0.55771706],
         [-1.70512824, -2.01165492]],

        [[-0.58358459, -1.69186794],
         [-0.71188866,  0.52618517]],

        [[ 2.206599  ,  0.22986657],
         [ 0.1470696 , -0.12139693]]],


       [[[-1.26950955,  1.51930681],
         [-1.50478947,  0.09201779]],

        [[ 1.98089238, -1.15927879],
         [-0.38889098,  1.09631793]],

        [[-0.44304926, -1.04254837],
         [-1.0459212 , -0.14205557]]]])

In [12]:
type(a)

numpy.ndarray

In [17]:
a = a.reshape(a.shape[0], a.shape[1], -1 )

In [18]:
a

array([[[-0.69353221,  0.55771706, -1.70512824, -2.01165492],
        [-0.58358459, -1.69186794, -0.71188866,  0.52618517],
        [ 2.206599  ,  0.22986657,  0.1470696 , -0.12139693]],

       [[-1.26950955,  1.51930681, -1.50478947,  0.09201779],
        [ 1.98089238, -1.15927879, -0.38889098,  1.09631793],
        [-0.44304926, -1.04254837, -1.0459212 , -0.14205557]]])

In [19]:
a.shape

(2, 3, 4)

In [22]:
list(a[0])

[array([-0.69353221,  0.55771706, -1.70512824, -2.01165492]),
 array([-0.58358459, -1.69186794, -0.71188866,  0.52618517]),
 array([ 2.206599  ,  0.22986657,  0.1470696 , -0.12139693])]

In [31]:

final = []

for i in range(len(a)):
    temp = [] # (out_ch, in_ch, k * k) -> list (k*k * ch)

    for j in range(len(a[i])):
        temp.append(list(a[i][j]))

    temp = np.concatenate(temp)
    temp = list(temp)

    final.append(temp)

final = np.concatenate(final)
final = list(final)
len(final)

24

In [83]:
def csv_conv_tensor(tensor, path='', name = ''):
    # tensor shape: (out, in, k, k)

    array = (tensor.data.cpu().detach().numpy())
    
    array = array.reshape(array.shape[0], array.shape[1], -1) # (out, in, k, k) -> (out, in, k * k)

    final = []
    
    for i in range(len(array)):
        temp = [] # HOLDS [ k * k * in]
        
        for j in range(len(array[i])):
            temp.append(list(array[i][j]))
        
        temp = np.concatenate(temp)
        temp = list(temp)
        
        final.append(temp)
    
    final = np.concatenate(final)
    df = pd.DataFrame(final)
    df.to_csv(path + f"{name}.csv", index = False)
    

In [84]:
import torch

import pandas as pd

path = "/home/tmahmud/Co-Design Tasks/Lab3_renew/Lab-3-Codesign/pruned_weights/"

tensor = torch.rand(2, 3, 3, 3)

csv_conv_tensor(tensor, path=path, name = 'Conv2D')


In [85]:
tensor = torch.rand(3, 2)
tensor

tensor([[0.1495, 0.8866],
        [0.5323, 0.4781],
        [0.1065, 0.3382]])

In [87]:
torch.concat(tensor.data, axis = 1)

TypeError: concat() received an invalid combination of arguments - got (Tensor, axis=int), but expected one of:
 * (tuple of Tensors tensors, int dim, *, Tensor out)
 * (tuple of Tensors tensors, name dim, *, Tensor out)


In [89]:
def csv_lin_tensor(tensor, path='', name = ''):

    array = (tensor.data.cpu().detach().numpy())
    
    array = array.reshape(array.shape[0], array.shape[1], -1) # (out, in, k, k) -> (out, in, k * k)

    final = []
    
    for i in range(len(array)):    
        final.append(list(array[i]))
    
    final = np.concatenate(final)

    df = pd.DataFrame(final)
    
    df.to_csv(path + f"{name}.csv", index = False)

In [90]:
tensor = torch.rand(3, 2)
csv_lin_tensor(tensor, path, 'lin')
tensor

tensor([[0.9147, 0.8458],
        [0.6895, 0.0235],
        [0.2476, 0.2819]])

In [8]:
def csv_conv_tensor(tensor, path='./pruned_weights/', name = ''):
    """
    Function to convert conv tensor data to 2D CSV file
      
    Input tensor shape: (out, in, k, k)

    Store CSV: (k * k * in * out)

    """
    array = (tensor.data.cpu().detach().numpy())
    
    array = array.reshape(array.shape[0], array.shape[1], -1) # (out, in, k, k) -> (out, in, k * k)

    final = []
    
    for i in range(len(array)):
        temp = [] # HOLDS [ k * k * in]
        
        for j in range(len(array[i])):
            temp.append(list(array[i][j]))
        
        temp = np.concatenate(temp)
        temp = list(temp)
        
        final.append(temp)
    
    final = np.concatenate(final)
    print(final)
    df = pd.DataFrame(final)
    df_transposed = df.T
    #print(df)
    if 'int' in name:
        df_transposed = df_transposed.astype(int)
    #df_transposed.to_csv(path + f"{name}.csv", index=False, header=False)

In [12]:
import torch
import numpy as np
import pandas as pd

In [5]:
a = torch.arange(18)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [7]:
a = a.view(2, 1, 3, 3)
a

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]]],


        [[[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]]])

In [13]:
csv_conv_tensor(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
     0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
